spring:
  application:
    name: myapp
  profiles:
    active: prod
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        instance-id: ${spring.application.name}:${random.value}
        prefer-ip-address: true
        acl-token: 1dc477e6-422b-33aa-4cc7-140e4386d030
management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
---
spring:
  config:
    activate:
      on-profile: '!local'
    import: vault://
  cloud:
    vault:
      authentication: APPROLE # TOKEN
      app-role:
        role-id: b6c35726-4ae4-7eed-8144-c23195a87e1d
        secret-id: 5f592301-ff49-0023-0bec-320c06a3bd7c
        role: pres-read
        app-role-path: approle
      # token: hvs.CAESIArHMmnKZLD521ZIaLumSAH9aCadoMm5UAF9eM_jWCh4Gh4KHGh2cy5rRXNVTk11TnVkR2JxQWFCbkhWZTBHWlc
      kv:
        enabled: true
        backend: secret
      uri: http://localhost:8200